-- Run this SQL once in Supabase > SQL Editor.
create table if not exists public.visitor_logs (
  id bigint generated by default as identity primary key,
  ip text not null,
  visited_at timestamptz not null default now(),
  path text,
  referrer text,
  user_agent text,
  gclid text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  request_id text
);

create index if not exists visitor_logs_ip_idx
  on public.visitor_logs (ip);

create index if not exists visitor_logs_visited_at_idx
  on public.visitor_logs (visited_at desc);

alter table public.visitor_logs enable row level security;
